name: coverity
on: push
env:
      COV_URL: https://coverity.identityguard.com
      COV_USER: committer-burlington
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      CSA: cov-analysis-linux64-2020.12

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Coverity Download
      run: |
        date
        curl -ksS --user $COV_USER:$COVERITY_PASSPHRASE $COV_URL/downloadFile.htm?fn=$CSA.tar.gz | tar -xzf -
        curl -ksS --user committer:Tester0_123! -o $CSA/bin/license.dat $COV_URL/downloadFile.htm?fn=license.dat
        ls -la
        $CSA/bin/cov-configure --java
