name: coverity

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
    - run: wget https://appsec-tools-docs.s3.amazonaws.com/Coverity/cov-analysis-linux64-2020.06.sh
    
